version: '2'
services:
  oracle-exporter:
    build:
      context: .
    ports:
     - "9161:9161"
    volumes:
    - /u01/app/diag/rdbms/db/db/trace/:/trace
    environment:
    - DATA_SOURCE_NAME=system/password@//localhost:1521/db
    - ORACLE_DATABASE=db
    - ORACLE_INSTANCE=db
    - ORACLE_ALERTLOG=/trace/alert_db.log

